### PR TITLE
Rename package to Winton.Extensions.Configuration.Consul

### PR DESCRIPTION
**Pull request by Choc13**
Changes
* Renaming of package and namespaces to `Winton.Extensions.Configuration.Consul`
* Remove deploy step from appveyor script to avoid publishing from my personal account for the time being. We will need to setup build from Winton account.

Addresses #1

### CODE REVIEW

**Comment by Choc13** [comment]
@ah- You have the ability to set up builds right? I think both travis and appveyor should work straight away with the current scripts, you'll just need to add the NuGet deploy keys on appveyor.

**Comment by ah-** [comment]
Builds are now running:
https://travis-ci.org/wintoncode/Winton.Extensions.Configuration.Consul
https://ci.appveyor.com/project/wintoncode/winton-extensions-configuration-consul

**Comment by ah-** [comment]
Could you try pushing something to this PR? I think they haven't quite picked up this PR yet.

**Comment by ah-** [comment]
The encrypted api key for nuget is: CxMH3k6k/Rpz1zjToGDAelLWDT/gDqRo08iEUAQsRnL+WRo+4TL5gLiNEUy/GfUy

You should be able to set it up similar to https://github.com/ah-/rdkafka-dotnet/blob/master/appveyor.yml

**Comment by Choc13** [comment]
Great thanks. I'll add the secret key and that should kick off the builds.

**Comment by Choc13** [comment]
Seems like the appveyor build is failing because it's cloned the repo in a detached head state and GitVersion doesn't like this. I wonder if it's because it's a fork that is being built. I can't see any settings in my previous appveyor setup that would solve this. Maybe we turn off versioning and publishing for PR builds and only run those steps for master builds?

**Comment by ah-** [comment]
Must be, looks like it's not on a proper branch when building a PR.

Probably we should only run gitversion of APPVEYOR_PULL_REQUEST_NUMBER is not empty?
https://www.appveyor.com/docs/environment-variables/

**Pull request merged**
