### PR TITLE
target netstandard2.0 and update references

### PR DESCRIPTION
**Pull request by govorovvs**

### CODE REVIEW

**Comment by Choc13** [comment]
Hi @govorovvs, thanks for the PR. I'd just like to understand your motivations for this change a bit more. It seems to me like you want this lib to reference `Microsoft.Extensions.Configuration 2.0.0` when the target framework is set to `netstandard2.0` is that correct?

**Comment by govorovvs** [comment]
Hi @Choc13, you are right!

**Comment by Choc13** [comment]
OK that makes sense. I had been wondering how to address this problem for a while, as obviously some lib users will want to use features in `Microsoft.Extensions.Configuration 2.0.0`. Ideally I'd like to avoid conditional package references but I'm not sure of another way around this problem. 

Out of interest are you seeing runtime or compile time failures when using this lib in a `netcoreapp2.0` project? We have used this lib along with `netcoreapp2.0` and the `Microsoft.AspNetCore.All 2.0.0` meta-package and didn't have any issues.

I'm now thinking that I could see a situation where someone would like to target `netcoreapp2.0` but use the ASP.NET Core 1.x libs. I appreciate that is probably a rare occurrence, but I think I need to think a bit more about this change first as it seems quite tricky to ensure maximum support.

Do you have any thoughts on the above points? Is there perhaps an example of another library that manages side-by-side support for different major version of ASP.NET Core?

**Comment by Choc13** [comment]
Sorry this has been quiet for a while. After giving it some careful thought I don't think this is right approach to solve this problem. I do not want to make the assumption that people targeting `netstandard2.0` are necessarily using ASP.NET Core 2.x, as there is nothing to say they aren't using ASP.NET Core 1.x whilst still targeting `netcoreapp2.0`. 

What I propose is that I will bump all versions of the other dependencies (namely `Consul` and `Newtonsoft.Json`) along with a bump to the minor versions of the ASP.NET Core packages to get them to the latest 1.1.x versions. I will then do a `1.1.0` release of this library which will also include your `ConfigureAwait` changes.

Once that is out then I will update this lib to start depending on `Microsoft.Extensions.Configuration 2.x` and at the same time bump the target framework to `netstandard2.0` as required by that package. I will then do another release of this lib at version 2.0.0. It was not my intention to do side-by-side major versioning of this library with the underlying `Microsoft.Extensions.Configuration` dependency, but in this case I think it is the most obvious solution and leads to least amount of maintenance overhead. I feel more strongly that I would like to avoid conditional compilation/dependencies based on the TFM. I'd be interested to hear your thoughts on this though.

**Pull request closed without merging**
