### PR TITLE
Enable pushing to nuget

### PR DESCRIPTION
**Pull request by ah-**
See https://ci.appveyor.com/project/wintoncode/winton-extensions-configuration-consul/build/10#L233

`configuration` isn't set at the moment.

### CODE REVIEW

**Comment by Choc13** [comment]
Do we not want to keep that but set build configuration to release? I suppose at the moment we are specifying the configuration in the build script dirctly rather than in the appveyor config.

**Comment by ah-** [comment]
That would be slightly nicer, how would you set it?

**Comment by Choc13** [comment]
I guess it would be more applicable if we're building the sln file rather than running a script and executing the dotnet commands directly. I guess it's one to revisit once they've sorted out the whole project.json / MSBuild thing as then we'll be able to just build the sln.

**Comment by ah-** [comment]
We have a nuget package!

https://www.nuget.org/packages/Winton.Extensions.Configuration.Consul

**Pull request merged**
