### PR TITLE
add persistence to local

### PR DESCRIPTION
**Pull request by trueai-org**
thanks

### CODE REVIEW

**Comment by Choc13** [comment]
Hi @trueai-org 

Thanks for taking the time to contribute. Before we start reviewing the code, could you please summarise what it is you would like to achieve here? From a quick read through it seems like you are trying to add some kind of offline caching mechanism for the config? But please could you tell me your specific use case so we can see if there a simpler way to achieve what you require.

Thanks.

**Comment by trueai-org** [comment]
> Hi @trueai-org
> 
> Thanks for taking the time to contribute. Before we start reviewing the code, could you please summarise what it is you would like to achieve here? From a quick read through it seems like you are trying to add some kind of offline caching mechanism for the config? But please could you tell me your specific use case so we can see if there a simpler way to achieve what you require.
> 
> Thanks.

Yes, added configuration for persistence
Every time when open the persistent, from the remote pull key/value, or consul changes, at the same time will be a local store
You are unable to connect to, consul will read local configuration
Test cases, in I submit code (Consul.Persistence.Sample), you can pull my branch testing master-trueai-org
for example:In consul add the key/value [test ...], the project execution directory will generate a corresponding [test.json] file

**Comment by trueai-org** [comment]
> > Hi @trueai-org
> > Thanks for taking the time to contribute. Before we start reviewing the code, could you please summarise what it is you would like to achieve here? From a quick read through it seems like you are trying to add some kind of offline caching mechanism for the config? But please could you tell me your specific use case so we can see if there a simpler way to achieve what you require.
> > Thanks.
> 
> Yes, added configuration for persistence
> When set persistence = "true", from the remote pull key/value, or consul changes, at the same time will be a local store
> You are unable to connect to, consul will read local configuration
> Test cases, in I submit code (Consul.Persistence.Sample), you can pull my branch testing master-trueai-org
> for example:In consul add the key/value [test ...], the project execution directory will generate a corresponding [test.json] file



> Hi @trueai-org
> 
> Thanks for taking the time to contribute. Before we start reviewing the code, could you please summarise what it is you would like to achieve here? From a quick read through it seems like you are trying to add some kind of offline caching mechanism for the config? But please could you tell me your specific use case so we can see if there a simpler way to achieve what you require.
> 
> Thanks.

In many project scenarios, Test in a variety of different environments, provide local persistence, can bring more convenience
In is not convenient to connect the consul, or for customer presentations, etc., to the appropriate directory replication configuration, the project can be started, lifted the dependence on consul in these scenarios.
I hope to get your support,
thanks

**Comment by trueai-org** [comment]
> In many project scenarios, Test in a variety of different environments, provide local persistence, can bring more convenience
> In is not convenient to connect the consul, or for customer presentations, etc., to the appropriate directory replication configuration, the project can be started, lifted the dependence on consul in these scenarios.
> I hope to get your support,
> thanks

**Comment by trueai-org** [comment]
@Choc13 

In many project scenarios, Test in a variety of different environments, provide local persistence, can bring more convenience
In is not convenient to connect the consul, or for customer presentations, etc., to the appropriate directory replication configuration, the project can be started, lifted the dependence on consul in these scenarios.
I hope to get your support,
thanks

**Comment by Choc13** [comment]
@trueai-org thanks for providing some more information. I have been thinking about this feature and I think we can probably address most of your problems without having to add caching to this library. 

Let's consider a few scenarios where Consul might not be available and how we can work around them without caching.
1) You would like to run the application for a presentation. In this case I would suggest using a different configuration provider, such as `AddJsonFile`. You could either toggle this based on the `IHostingEnvironment` when setting up your config in `Program.cs` or you could call `AddJsonFile` first and then call `AddConsul` and set it as optional so that if consul was not available it would not fail to start the application.
2) The application is already running and Consul goes down. This should not be a problem as the config will already be in the ASP.NET Core configuration system and so it is in effect cached. Obviously, if you have told the Consul provider to watch for changes then you might see some errors there, but they can be handled by setting the `OnWatchException` option.
3) The application has restarted and now Consul is no longer available. This seems to be the case that you solution would be most useful in. However, Consul is designed to be highly available and it's primary purpose is for application / service discovery, so if Consul is down there most likely bigger issues that would prevent your application from working anyway. Also, given that many applications that utilise Consul are likely deployed to some sort of virtualised elastic environment, like the cloud, then we can't really assume they have the ability to write to disk. Furthermore, there is not guarantee that an application will even be restarted on the same machine and so we cannot guarantee that the file that was written to cache the config will still be there.

Overall, I feel like there are already mechanisms in place, either in this library or the ASP.NET Core config system, that will allow you to be resilient to Consul downtime without us having to add caching here. The cases where caching could be useful are probably too rare to warrant the additional complexity that a would be required to add a caching system here that would be flexible enough to work in all types of hosting environment.

I hope you are able to use this information to solve you specific problem, but I am going to close this PR as I don't think is something we want to add to this library.

**Pull request closed without merging**
