### PR TITLE
Change from NUnit to XUnit.

### PR DESCRIPTION
**Pull request by Choc13**

### CODE REVIEW

**Comment by jhickson** [comment]
Why change from NUnit to Xunit?

**Comment by Choc13** [comment]
@jhickson for a few reasons:
1) Microsoft seem to have backed it vs NUnit, which was apparent when .NET Core was in its early days and XUnit was the only test frame work that properly worked, which I believe was because MS worked closely with them and gave them access to pre-releases to ensure that there was a test framework available immediately.
2) I find its setup to be more natural in that it uses the test classes constructor, which allows fields to be marked readonly.
3) It has better compiler integration as it causes a compiler error if a test class is not marked public for example, or if `[InlineData]` is used with a `[Fact]` rather than a `[Theory]`.
4) Similar to 3, it allows test case methods to be marked `private` which means there is an intellisense warning in VS if someone forgets to add the `[Fact]` or `[Theory]`. So it's easier to spot those mistakes.

**Comment by jhickson** [comment]
OK. I'm not sure (1) is valid otherwise we'd only be using MS-approved stuff! Otherwise I can sympathise. I use XUnit in the Actor project because, as you say, NUnit lacked support at the time. XUnit's range of assertions is not great but using it with FluentAssertions make up for that.

Happy to approve once the Travis and Appveyor failures have been addressed.

**Comment by Choc13** [comment]
I'm not suggesting we only use MS-approved stuff, it's more that because the .NET Core and ASP.NET Core dev teams seem to use xUnit it means it's more likely to be updated quicker.

**Pull request merged**
