### PR TITLE
Update to Microsoft.Extensions.Configuration version 3.

### PR DESCRIPTION
**Pull request by Choc13**
* Updates the `Microsoft.Extensions.Configuration` dependency to version 3.
* Updates the test projects to `netcoreapp3.0`.
* As this library tracks the major version of `Microsoft.Extensions.Configuration` this will cause a breaking change.
* There is a potential question to be addressed here as to whether we should use the new `System.Text.Json` instead of `Newtonsoft.Json`. The `Consul` dependency brings `NewtonSoft.Json` in anyway, so we already have access to that dependency transitively, but on the other hand the [`JsonConfigurationProvider`](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Json/src/JsonConfigurationFileParser.cs) has moved to using `System.Text.Json`.

### CODE REVIEW

**Comment by gitfool** [comment]
I'm curious... can you simplify this provider by leveraging [JsonStreamConfigurationProvider](https://github.com/aspnet/Extensions/blob/master/src/Configuration/Config.Json/src/JsonStreamConfigurationProvider.cs) to handle all things JSON? (I'm wondering if I can do the same but for YAML extraction.) Ideally, this library is just concerned with Consul as a configuration source and not much else.

**Comment by Choc13** [comment]
@gitfool that was actually my original intention when I designed this back in v1 as I completely agree that this library doesn't want to have to concern itself with parsing different formats that might be stored in Consul. However, back then the JSON parser was internal to the JSON configuration provider library and so there was no way to extend Microsoft's JSON provider. However, from your link it seems they have refactored their code now and so it looks like it might be possible. I will investigate further and make those changes in separate PR if it works out.

**Comment by gitfool** [comment]
Cool. I'll see how you do it, assuming it works, so I can try to apply the same approach to delegating to something like [NetEscapades.Configuration](https://github.com/andrewlock/NetEscapades.Configuration) for handling YAML.

**Comment by Choc13** [comment]
OK so I think we can utilise `JsonStreamConfigurationProvider`, but perhaps not in the way you were expecting / hoping. It's straightforward enough to update the `JsonConfigurationParser` in this lib to just be (this is untested by the way, but I don't see why it shouldn't work):

```
public IDictionary<string, string> Parse(Stream stream)
{
    return new ConfigurationBuilder()
           .AddJsonStream(stream)
           .Build()
           .AsEnumerable()
           .ToDictionary(pair => pair.Key, pair => pair.Value);
}
``` 

Which obviously simplifies that by leveraging their JSON parsing, but it only really works because they have a provider that takes a stream. 

I'm not sure if this is what you were thinking originally, but it's not really possible to make the provider in this lib extend any of the ones provided by Microsoft, such as `StreamConfigurationProvider` or `FileConfigurationProvider` because they have specific semantics about streams and files respectively, which do not make sense in our case. For instance the `StreamConfigurationProvider` has no reload capabilities as it just parses the stream that was passed to it from the `StreamConfigurationSource` once and is then done (hence why we can use it in the way I have done above). 

Another point to consider is that the configuration in our case in general consists of multiple streams. We might end up receiving multiple `KvPairs` from Consul that reside under a given root key, and so this lib is merging all of those into a single `IDictionary<string, string>` by applying the parser to the stream that we get from the value of each `KvPair`, under the assumption that every key under a given root is encoded in the same format.

So I think we either need to keep the `IConfigurationParser` property on `IConsulConfigurationSource` to allow people to choose different parsers, or we copy the design MS have gone for and have an `abstract` `ConsulConfigurationProvider` with concretions such as `JsonConsulConfigurationProvider`. Either way, you'd still need to define a method that can create an `IDictionary<string, string>` from a `Stream` for each type of encoding. Unless you have any other ideas, I realise my thinking might be clouded a lot by the current implementation?

**Comment by Choc13** [comment]
Looking at the NetEscapades.Configuration library I'm not sure it's possible to leverage their parser. It requires a physical file to use it directly, which would mean writing the config we back to disk (not really an option). To extend it would mean sub-classing `YamlConfigurationProvider` and therefore `YamlConfigurationSource` which themselves sub-class `FileConfigurationProvider` and `FileConfigurationSource` and again these are very file oriented APIs which wouldn't make sense for consumers of this lib.

It's a shame that these configuration providers don't compose better.

**Comment by gitfool** [comment]
Thanks for looking into it. Yeah it looks like these providers don't compose nicely, as I'd hoped. Ultimately, `NetEscapades.Configuration` does have a [parser](https://github.com/andrewlock/NetEscapades.Configuration/blob/master/src/NetEscapades.Configuration.Yaml/YamlConfigurationFileParser.cs#L16) that expects a `Stream` and returns `IDictionary<string, string>`, so I could leverage that as you did above via [YamlConfigurationProvider](https://github.com/andrewlock/NetEscapades.Configuration/blob/master/src/NetEscapades.Configuration.Yaml/YamlConfigurationProvider.cs#L20). I could also use reflection or ask Andrew to expose the parser. At least there are options!

Do you think you'll still leverage `JsonStreamConfigurationProvider`? It does have advantages...

**Comment by Choc13** [comment]
I'm in two minds about it currently. On the one hand it removes my explicit dependency on `NewtonSoft.Json` and, like you already pointed out, keeps this lib more focused on the Consul side of things without worrying about parsing Json. This is code I'd rather not have to maintain when MS clearly have a well tested implementation themselves.

On the other hand it does mean I have to take an explicit dependency on the `Microsoft.Extensions.Configuration.Json` package. Not a huge issue in itself, but I'd rather this lib didn't accrete lots of dependencies just for the sake of parsing. Particularly as it could mean for many users having deps being brought in that they have no use for (e.g. someone just wants to parse simple values from Consul, but now has JSON and Yaml parsing packages too). One option would be to then split this into a package per encoding (as MS do), but also seems like overkill right now for the few that we are likely to support. I'll think about it some more.

**Pull request merged**
